---
- name: Configure PopOS!
  hosts: localhost
  become: true

- name: Flatpak
  import_playbook: playbooks/flatpak.ansible.yml

- name: APT
  import_playbook: playbooks/apt.ansible.yml

# - name: GNOME
#   import_playbook: playbooks/gnome.ansible.yml

- name: Clone some interesting projects to work with
  import_playbook: playbooks/projects.ansible.yml
