---
- name: APT
  hosts: localhost
  become: true

  tasks:
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true
        autoremove: true

    - name: Install development packages
      ansible.builtin.apt:
        pkg:
          - unzip
          # - starship
          - exa
          - bat
          - fortune
          # - pfetch
          - htop
          - nmap
          # - boosteroid
          - chat-gpt
          - cloc
          - code
          # - pnpm
          # - fisher
          - fish
          - httpie
          - peco
          - ripgrep
          - jq
          -

    - name: Remove development tools
      ansible.builtin.apt:
        pkg:
          - crystal
          - elixir
          - cmake
          - julia
          - wrk
        state: absent
